"""Typed `ask` surfaces. GENERATED by `scripts/gen_ask_overloads.py`; do not edit.

Every shape whose types `ask` carries through is written out as an overload,
because Python cannot map a type over a tuple. Any nesting still works at
runtime; the forms below are the ones a type checker can follow.

Regenerate with `mise run gen`.
"""

from abc import ABC, abstractmethod
from collections.abc import Awaitable
from typing import overload

from guideme._json import Json
from guideme.question import Question


class SyncAskOverloads(ABC):
    """The typed `ask` surface of `Guide`; `_ask` does the work."""

    @abstractmethod
    def _ask(self, shape: object, state: Json) -> object: ...

    @overload
    def ask[T](
        self,
        shape: Question[T],
        state: Json,
    ) -> T: ...

    @overload
    def ask[T](
        self,
        shape: list[Question[T]],
        state: Json,
    ) -> list[T]: ...

    @overload
    def ask[K, T](
        self,
        shape: dict[K, Question[T]],
        state: Json,
    ) -> dict[K, T]: ...

    @overload
    def ask[T0](
        self,
        shape: tuple[Question[T0]],
        state: Json,
    ) -> tuple[T0]: ...

    @overload
    def ask[T0, T1](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
        ],
        state: Json,
    ) -> tuple[T0, T1]: ...

    @overload
    def ask[T0, T1, T2](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            Question[T2],
        ],
        state: Json,
    ) -> tuple[T0, T1, T2]: ...

    @overload
    def ask[T0, T1, T2, T3](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            Question[T2],
            Question[T3],
        ],
        state: Json,
    ) -> tuple[T0, T1, T2, T3]: ...

    @overload
    def ask[T0, T1, T2, T3, T4](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            Question[T2],
            Question[T3],
            Question[T4],
        ],
        state: Json,
    ) -> tuple[T0, T1, T2, T3, T4]: ...

    @overload
    def ask[T0, T1, T2, T3, T4, T5](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            Question[T2],
            Question[T3],
            Question[T4],
            Question[T5],
        ],
        state: Json,
    ) -> tuple[T0, T1, T2, T3, T4, T5]: ...

    @overload
    def ask[T0, T1, T2, T3, T4, T5, T6](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            Question[T2],
            Question[T3],
            Question[T4],
            Question[T5],
            Question[T6],
        ],
        state: Json,
    ) -> tuple[T0, T1, T2, T3, T4, T5, T6]: ...

    @overload
    def ask[T0, T1, T2, T3, T4, T5, T6, T7](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            Question[T2],
            Question[T3],
            Question[T4],
            Question[T5],
            Question[T6],
            Question[T7],
        ],
        state: Json,
    ) -> tuple[T0, T1, T2, T3, T4, T5, T6, T7]: ...

    @overload
    def ask[T0, K, T](
        self,
        shape: tuple[
            Question[T0],
            dict[K, Question[T]],
        ],
        state: Json,
    ) -> tuple[T0, dict[K, T]]: ...

    @overload
    def ask[T0, T1, K, T](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            dict[K, Question[T]],
        ],
        state: Json,
    ) -> tuple[T0, T1, dict[K, T]]: ...

    @overload
    def ask[T0, T1, T2, K, T](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            Question[T2],
            dict[K, Question[T]],
        ],
        state: Json,
    ) -> tuple[T0, T1, T2, dict[K, T]]: ...

    @overload
    def ask[T0, T1, T2, T3, K, T](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            Question[T2],
            Question[T3],
            dict[K, Question[T]],
        ],
        state: Json,
    ) -> tuple[T0, T1, T2, T3, dict[K, T]]: ...

    @overload
    def ask[T0, T1, T2, T3, T4, K, T](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            Question[T2],
            Question[T3],
            Question[T4],
            dict[K, Question[T]],
        ],
        state: Json,
    ) -> tuple[T0, T1, T2, T3, T4, dict[K, T]]: ...

    @overload
    def ask[T0, T1, T2, T3, T4, T5, K, T](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            Question[T2],
            Question[T3],
            Question[T4],
            Question[T5],
            dict[K, Question[T]],
        ],
        state: Json,
    ) -> tuple[T0, T1, T2, T3, T4, T5, dict[K, T]]: ...

    @overload
    def ask[T0, T1, T2, T3, T4, T5, T6, K, T](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            Question[T2],
            Question[T3],
            Question[T4],
            Question[T5],
            Question[T6],
            dict[K, Question[T]],
        ],
        state: Json,
    ) -> tuple[T0, T1, T2, T3, T4, T5, T6, dict[K, T]]: ...

    @overload
    def ask[T0, T](
        self,
        shape: tuple[
            Question[T0],
            list[Question[T]],
        ],
        state: Json,
    ) -> tuple[T0, list[T]]: ...

    @overload
    def ask[T0, T1, T](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            list[Question[T]],
        ],
        state: Json,
    ) -> tuple[T0, T1, list[T]]: ...

    @overload
    def ask[T0, T1, T2, T](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            Question[T2],
            list[Question[T]],
        ],
        state: Json,
    ) -> tuple[T0, T1, T2, list[T]]: ...

    @overload
    def ask[T0, T1, T2, T3, T](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            Question[T2],
            Question[T3],
            list[Question[T]],
        ],
        state: Json,
    ) -> tuple[T0, T1, T2, T3, list[T]]: ...

    @overload
    def ask[T0, T1, T2, T3, T4, T](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            Question[T2],
            Question[T3],
            Question[T4],
            list[Question[T]],
        ],
        state: Json,
    ) -> tuple[T0, T1, T2, T3, T4, list[T]]: ...

    @overload
    def ask[T0, T1, T2, T3, T4, T5, T](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            Question[T2],
            Question[T3],
            Question[T4],
            Question[T5],
            list[Question[T]],
        ],
        state: Json,
    ) -> tuple[T0, T1, T2, T3, T4, T5, list[T]]: ...

    @overload
    def ask[T0, T1, T2, T3, T4, T5, T6, T](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            Question[T2],
            Question[T3],
            Question[T4],
            Question[T5],
            Question[T6],
            list[Question[T]],
        ],
        state: Json,
    ) -> tuple[T0, T1, T2, T3, T4, T5, T6, list[T]]: ...

    def ask(self, shape: object, state: Json) -> object:
        """Answer `shape` about `state` in one request and one `guideme.ask` span."""
        return self._ask(shape, state)


class AsyncAskOverloads(ABC):
    """The typed `ask` surface of `AsyncGuide`; `_ask` does the work."""

    @abstractmethod
    def _ask(self, shape: object, state: Json) -> Awaitable[object]: ...

    @overload
    def ask[T](
        self,
        shape: Question[T],
        state: Json,
    ) -> Awaitable[T]: ...

    @overload
    def ask[T](
        self,
        shape: list[Question[T]],
        state: Json,
    ) -> Awaitable[list[T]]: ...

    @overload
    def ask[K, T](
        self,
        shape: dict[K, Question[T]],
        state: Json,
    ) -> Awaitable[dict[K, T]]: ...

    @overload
    def ask[T0](
        self,
        shape: tuple[Question[T0]],
        state: Json,
    ) -> Awaitable[tuple[T0]]: ...

    @overload
    def ask[T0, T1](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
        ],
        state: Json,
    ) -> Awaitable[tuple[T0, T1]]: ...

    @overload
    def ask[T0, T1, T2](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            Question[T2],
        ],
        state: Json,
    ) -> Awaitable[tuple[T0, T1, T2]]: ...

    @overload
    def ask[T0, T1, T2, T3](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            Question[T2],
            Question[T3],
        ],
        state: Json,
    ) -> Awaitable[tuple[T0, T1, T2, T3]]: ...

    @overload
    def ask[T0, T1, T2, T3, T4](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            Question[T2],
            Question[T3],
            Question[T4],
        ],
        state: Json,
    ) -> Awaitable[tuple[T0, T1, T2, T3, T4]]: ...

    @overload
    def ask[T0, T1, T2, T3, T4, T5](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            Question[T2],
            Question[T3],
            Question[T4],
            Question[T5],
        ],
        state: Json,
    ) -> Awaitable[tuple[T0, T1, T2, T3, T4, T5]]: ...

    @overload
    def ask[T0, T1, T2, T3, T4, T5, T6](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            Question[T2],
            Question[T3],
            Question[T4],
            Question[T5],
            Question[T6],
        ],
        state: Json,
    ) -> Awaitable[tuple[T0, T1, T2, T3, T4, T5, T6]]: ...

    @overload
    def ask[T0, T1, T2, T3, T4, T5, T6, T7](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            Question[T2],
            Question[T3],
            Question[T4],
            Question[T5],
            Question[T6],
            Question[T7],
        ],
        state: Json,
    ) -> Awaitable[tuple[T0, T1, T2, T3, T4, T5, T6, T7]]: ...

    @overload
    def ask[T0, K, T](
        self,
        shape: tuple[
            Question[T0],
            dict[K, Question[T]],
        ],
        state: Json,
    ) -> Awaitable[tuple[T0, dict[K, T]]]: ...

    @overload
    def ask[T0, T1, K, T](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            dict[K, Question[T]],
        ],
        state: Json,
    ) -> Awaitable[tuple[T0, T1, dict[K, T]]]: ...

    @overload
    def ask[T0, T1, T2, K, T](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            Question[T2],
            dict[K, Question[T]],
        ],
        state: Json,
    ) -> Awaitable[tuple[T0, T1, T2, dict[K, T]]]: ...

    @overload
    def ask[T0, T1, T2, T3, K, T](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            Question[T2],
            Question[T3],
            dict[K, Question[T]],
        ],
        state: Json,
    ) -> Awaitable[tuple[T0, T1, T2, T3, dict[K, T]]]: ...

    @overload
    def ask[T0, T1, T2, T3, T4, K, T](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            Question[T2],
            Question[T3],
            Question[T4],
            dict[K, Question[T]],
        ],
        state: Json,
    ) -> Awaitable[tuple[T0, T1, T2, T3, T4, dict[K, T]]]: ...

    @overload
    def ask[T0, T1, T2, T3, T4, T5, K, T](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            Question[T2],
            Question[T3],
            Question[T4],
            Question[T5],
            dict[K, Question[T]],
        ],
        state: Json,
    ) -> Awaitable[tuple[T0, T1, T2, T3, T4, T5, dict[K, T]]]: ...

    @overload
    def ask[T0, T1, T2, T3, T4, T5, T6, K, T](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            Question[T2],
            Question[T3],
            Question[T4],
            Question[T5],
            Question[T6],
            dict[K, Question[T]],
        ],
        state: Json,
    ) -> Awaitable[tuple[T0, T1, T2, T3, T4, T5, T6, dict[K, T]]]: ...

    @overload
    def ask[T0, T](
        self,
        shape: tuple[
            Question[T0],
            list[Question[T]],
        ],
        state: Json,
    ) -> Awaitable[tuple[T0, list[T]]]: ...

    @overload
    def ask[T0, T1, T](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            list[Question[T]],
        ],
        state: Json,
    ) -> Awaitable[tuple[T0, T1, list[T]]]: ...

    @overload
    def ask[T0, T1, T2, T](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            Question[T2],
            list[Question[T]],
        ],
        state: Json,
    ) -> Awaitable[tuple[T0, T1, T2, list[T]]]: ...

    @overload
    def ask[T0, T1, T2, T3, T](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            Question[T2],
            Question[T3],
            list[Question[T]],
        ],
        state: Json,
    ) -> Awaitable[tuple[T0, T1, T2, T3, list[T]]]: ...

    @overload
    def ask[T0, T1, T2, T3, T4, T](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            Question[T2],
            Question[T3],
            Question[T4],
            list[Question[T]],
        ],
        state: Json,
    ) -> Awaitable[tuple[T0, T1, T2, T3, T4, list[T]]]: ...

    @overload
    def ask[T0, T1, T2, T3, T4, T5, T](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            Question[T2],
            Question[T3],
            Question[T4],
            Question[T5],
            list[Question[T]],
        ],
        state: Json,
    ) -> Awaitable[tuple[T0, T1, T2, T3, T4, T5, list[T]]]: ...

    @overload
    def ask[T0, T1, T2, T3, T4, T5, T6, T](
        self,
        shape: tuple[
            Question[T0],
            Question[T1],
            Question[T2],
            Question[T3],
            Question[T4],
            Question[T5],
            Question[T6],
            list[Question[T]],
        ],
        state: Json,
    ) -> Awaitable[tuple[T0, T1, T2, T3, T4, T5, T6, list[T]]]: ...

    def ask(self, shape: object, state: Json) -> Awaitable[object]:
        """Answer `shape` about `state` in one request and one `guideme.ask` span."""
        return self._ask(shape, state)
