"""Generate `src/guideme/_ask_overloads.py`.

Python has no type-level map over a tuple, so every shape `ask` types has to be
written out as an overload. Writing them twice, once for `Guide` and once for
`AsyncGuide`, is how the two surfaces would drift, so both come from one
description here and `mise run gen-check` fails when the file is stale.

The output is already formatted: every signature is exploded with a trailing
comma, which is what keeps `ruff format` from rewriting it.
"""

MAX_TUPLE = 8
"""Longest tuple of questions that carries its types through."""

ASK_DOC = '''"""Answer `shape` about `state` in one request and one `guideme.ask` span.

A batch is atomic: one answer the policy cannot resolve fails the whole call, so
put `.otherwise(...)` or `.detail()` on the questions that may come back unsure.

Args:
    shape: A question, or a tuple, list or dict of questions, nested freely.
        Ids are `q0..qN` in encounter order, and the answer has the shape of
        the request.
    state: What to judge, as anything JSON-shaped.

Returns:
    The answers, in the shape of `shape`.

Raises:
    ConfigError: `shape` holds something that is not a question, a question's
        own thresholds are outside `0..=1` or leave `no_below` above
        `yes_above`, the batch is empty, or `state` or the instructions cannot
        be serialised to JSON. A rubric this call could not ask is refused
        where the question is built, not here.
    UnsureError: the policy read an answer as unsure and neither
        `.otherwise(...)` nor a `fallback(...)` member caught it.
    ProtocolError: the response breaks the contract: an undecodable body, the
        wrong answer kind, an option or level outside the rubric, or a
        probability outside `0..=1`.
    AuthError: the key was refused (`401`).
    InvalidError: the API rejected the request (`422`).
    RateLimitedError: still throttled after the retries (`429`).
    OverloadedError: still overloaded after the retries (`529`).
    TransportError: the request never completed: connection, TLS or timeout.
    UnexpectedStatusError: a status the contract does not define.
"""'''
"""The docstring on every generated `ask`. It is the package's main verb, and with
`py.typed` shipped this is what a caller's editor shows."""

RECEIPT_DOC = '''"""Answer `shape` about `state`, with what the request cost and what answered it.

Exactly `ask`, returning a `Receipt` instead of the answer alone: `ask` is this
call followed by `.answer`. Reach for it to attribute cost, or to pin a policy to
the model version whose numbers it was tuned against, and note that `model` is
the versioned id even where an alias such as `jev-latest` was asked for.

Args:
    shape: A question, or a tuple, list or dict of questions, nested freely.
        Ids are `q0..qN` in encounter order, and `Receipt.answer` has the
        shape of the request.
    state: What to judge, as anything JSON-shaped.

Returns:
    A `Receipt` carrying the answers, the model that produced them, and the
    token usage of the one request they came from.

Raises:
    The same errors as `ask`, on the same terms.
"""'''
"""The docstring on every generated `ask_with_receipt`. It defers to `ask`'s rather
than repeating nine `Raises:` lines that would then have to be kept in step."""

HEADER = '''"""Typed `ask` surfaces. GENERATED by `scripts/gen_ask_overloads.py`; do not edit.

Every shape whose types `ask` carries through is written out as an overload,
because Python cannot map a type over a tuple. Any nesting still works at
runtime; the forms below are the ones a type checker can follow. Each verb
carries the same family twice over, once returning the answer and once
returning a `Receipt` around it.

Regenerate with `mise run gen`.
"""

# pylint: disable=too-many-lines  # 25 shapes x 2 verbs x 2 surfaces, all of it generated

from abc import ABC, abstractmethod
from collections.abc import Awaitable
from typing import overload

from guideme._json import Json
from guideme.question import Question
from guideme.receipt import Receipt
'''


def shapes() -> list[tuple[str, str, str]]:
    """Every typed shape as `(type parameters, shape type, answer type)`."""
    forms = [
        ("T", "Question[T]", "T"),
        ("T", "list[Question[T]]", "list[T]"),
        ("K, T", "dict[K, Question[T]]", "dict[K, T]"),
    ]
    for size in range(1, MAX_TUPLE + 1):
        names = [f"T{i}" for i in range(size)]
        questions = [f"Question[{name}]" for name in names]
        forms.append(
            (
                ", ".join(names),
                f"tuple[{', '.join(questions)}]",
                f"tuple[{', '.join(names)}]",
            )
        )
    trailing = (
        ("K, T", "dict[K, Question[T]]", "dict[K, T]"),
        ("T", "list[Question[T]]", "list[T]"),
    )
    for extra, container, answer in trailing:
        for size in range(1, MAX_TUPLE):
            names = [f"T{i}" for i in range(size)]
            questions = [f"Question[{name}]" for name in names]
            forms.append(
                (
                    f"{', '.join(names)}, {extra}",
                    f"tuple[{', '.join([*questions, container])}]",
                    f"tuple[{', '.join([*names, answer])}]",
                )
            )
    return forms


def elements(inner: str) -> list[str]:
    """Split a subscript on its top-level commas, so `dict[K, V]` stays in one piece."""
    parts: list[str] = []
    depth = 0
    current = ""
    for character in inner:
        if character == "[":
            depth += 1
        elif character == "]":
            depth -= 1
        if character == "," and not depth:
            parts.append(current.strip())
            current = ""
        else:
            current += character
    parts.append(current.strip())
    return parts


def shape_lines(shape: str) -> list[str]:
    """Render the shape parameter, exploded when it is a tuple of more than one element."""
    if not shape.startswith("tuple["):
        return [f"        shape: {shape},"]
    inner = elements(shape.removeprefix("tuple[").removesuffix("]"))
    if len(inner) == 1:
        return [f"        shape: {shape},"]
    return [
        "        shape: tuple[",
        *[f"            {element}," for element in inner],
        "        ],",
    ]


def returned(answer: str, *, is_async: bool, wrapped: bool) -> str:
    """What one signature returns: the answer, maybe in a `Receipt`, maybe awaitable."""
    inner = f"Receipt[{answer}]" if wrapped else answer
    return f"Awaitable[{inner}]" if is_async else inner


def overload_lines(
    verb: str, parameters: str, shape: str, answer: str, *, is_async: bool, wrapped: bool
) -> list[str]:
    """One `@overload` declaration, in the shape `ruff format` leaves alone."""
    return [
        "    @overload",
        f"    def {verb}[{parameters}](",
        "        self,",
        *shape_lines(shape),
        "        state: Json,",
        f"    ) -> {returned(answer, is_async=is_async, wrapped=wrapped)}: ...",
    ]


def doc_lines(doc: str, indent: str) -> list[str]:
    """Indent a docstring to `indent`, leaving its blank lines truly blank."""
    return [f"{indent}{line}" if line else "" for line in doc.splitlines()]


def verb_lines(verb: str, doc: str, *, is_async: bool, wrapped: bool) -> list[str]:
    """One public verb: its whole overload family, then the implementation they cover."""
    lines: list[str] = []
    for parameters, shape, answer in shapes():
        lines.append("")
        lines += overload_lines(verb, parameters, shape, answer, is_async=is_async, wrapped=wrapped)
    returns = returned("object", is_async=is_async, wrapped=wrapped)
    lines += [
        "",
        f"    def {verb}(self, shape: object, state: Json) -> {returns}:",
        *doc_lines(doc, "        "),
        f"        return self._{verb}(shape, state)",
    ]
    return lines


def surface(name: str, summary: str, *, is_async: bool) -> list[str]:
    """One overload-carrying base class, sync or async."""
    plain = returned("object", is_async=is_async, wrapped=False)
    receipt = returned("object", is_async=is_async, wrapped=True)
    lines = [
        f"class {name}(ABC):",
        f'    """{summary}"""',
        "",
        "    @abstractmethod",
        f"    def _ask(self, shape: object, state: Json) -> {plain}: ...",
        "",
        "    @abstractmethod",
        f"    def _ask_with_receipt(self, shape: object, state: Json) -> {receipt}: ...",
    ]
    lines += verb_lines("ask", ASK_DOC, is_async=is_async, wrapped=False)
    lines += verb_lines("ask_with_receipt", RECEIPT_DOC, is_async=is_async, wrapped=True)
    return lines


def main() -> None:
    """Print the module."""
    lines = HEADER.splitlines()
    lines += ["", ""]
    lines += surface(
        "SyncAskOverloads",
        "The typed `ask` surfaces of `Guide`; the two `_ask` methods do the work.",
        is_async=False,
    )
    lines += ["", ""]
    lines += surface(
        "AsyncAskOverloads",
        "The typed `ask` surfaces of `AsyncGuide`; the two `_ask` methods do the work.",
        is_async=True,
    )
    print("\n".join(lines))


if __name__ == "__main__":
    main()
