"""Generate `src/guideme/_ask_overloads.py`.

Python has no type-level map over a tuple, so every shape `ask` types has to be
written out as an overload. Writing them twice, once for `Guide` and once for
`AsyncGuide`, is how the two surfaces would drift, so both come from one
description here and `mise run gen-check` fails when the file is stale.

The output is already formatted: every signature is exploded with a trailing
comma, which is what keeps `ruff format` from rewriting it.
"""

MAX_TUPLE = 8
"""Longest tuple of questions that carries its types through."""

ASK_DOC = '"""Answer `shape` about `state` in one request and one `guideme.ask` span."""'

HEADER = '''"""Typed `ask` surfaces. GENERATED by `scripts/gen_ask_overloads.py`; do not edit.

Every shape whose types `ask` carries through is written out as an overload,
because Python cannot map a type over a tuple. Any nesting still works at
runtime; the forms below are the ones a type checker can follow.

Regenerate with `mise run gen`.
"""

from abc import ABC, abstractmethod
from collections.abc import Awaitable
from typing import overload

from guideme._json import Json
from guideme.question import Question
'''


def shapes() -> list[tuple[str, str, str]]:
    """Every typed shape as `(type parameters, shape type, answer type)`."""
    forms = [
        ("T", "Question[T]", "T"),
        ("T", "list[Question[T]]", "list[T]"),
        ("K, T", "dict[K, Question[T]]", "dict[K, T]"),
    ]
    for size in range(1, MAX_TUPLE + 1):
        names = [f"T{i}" for i in range(size)]
        questions = [f"Question[{name}]" for name in names]
        forms.append(
            (
                ", ".join(names),
                f"tuple[{', '.join(questions)}]",
                f"tuple[{', '.join(names)}]",
            )
        )
    trailing = (
        ("K, T", "dict[K, Question[T]]", "dict[K, T]"),
        ("T", "list[Question[T]]", "list[T]"),
    )
    for extra, container, answer in trailing:
        for size in range(1, MAX_TUPLE):
            names = [f"T{i}" for i in range(size)]
            questions = [f"Question[{name}]" for name in names]
            forms.append(
                (
                    f"{', '.join(names)}, {extra}",
                    f"tuple[{', '.join([*questions, container])}]",
                    f"tuple[{', '.join([*names, answer])}]",
                )
            )
    return forms


def elements(inner: str) -> list[str]:
    """Split a subscript on its top-level commas, so `dict[K, V]` stays in one piece."""
    parts: list[str] = []
    depth = 0
    current = ""
    for character in inner:
        if character == "[":
            depth += 1
        elif character == "]":
            depth -= 1
        if character == "," and not depth:
            parts.append(current.strip())
            current = ""
        else:
            current += character
    parts.append(current.strip())
    return parts


def shape_lines(shape: str) -> list[str]:
    """Render the shape parameter, exploded when it is a tuple of more than one element."""
    if not shape.startswith("tuple["):
        return [f"        shape: {shape},"]
    inner = elements(shape.removeprefix("tuple[").removesuffix("]"))
    if len(inner) == 1:
        return [f"        shape: {shape},"]
    return [
        "        shape: tuple[",
        *[f"            {element}," for element in inner],
        "        ],",
    ]


def overload_lines(parameters: str, shape: str, answer: str, *, is_async: bool) -> list[str]:
    """One `@overload` declaration, in the shape `ruff format` leaves alone."""
    returns = f"Awaitable[{answer}]" if is_async else answer
    return [
        "    @overload",
        f"    def ask[{parameters}](",
        "        self,",
        *shape_lines(shape),
        "        state: Json,",
        f"    ) -> {returns}: ...",
    ]


def surface(name: str, summary: str, *, is_async: bool) -> list[str]:
    """One overload-carrying base class, sync or async."""
    returns = "Awaitable[object]" if is_async else "object"
    lines = [
        f"class {name}(ABC):",
        f'    """{summary}"""',
        "",
        "    @abstractmethod",
        f"    def _ask(self, shape: object, state: Json) -> {returns}: ...",
    ]
    for parameters, shape, answer in shapes():
        lines.append("")
        lines += overload_lines(parameters, shape, answer, is_async=is_async)
    lines += [
        "",
        f"    def ask(self, shape: object, state: Json) -> {returns}:",
        f"        {ASK_DOC}",
        "        return self._ask(shape, state)",
    ]
    return lines


def main() -> None:
    """Print the module."""
    lines = HEADER.splitlines()
    lines += ["", ""]
    lines += surface(
        "SyncAskOverloads",
        "The typed `ask` surface of `Guide`; `_ask` does the work.",
        is_async=False,
    )
    lines += ["", ""]
    lines += surface(
        "AsyncAskOverloads",
        "The typed `ask` surface of `AsyncGuide`; `_ask` does the work.",
        is_async=True,
    )
    print("\n".join(lines))


if __name__ == "__main__":
    main()
